# Generated by Django 2.2.4 on 2019-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms',
            field=models.BooleanField(default=True),
        ),
    ]
