# Generated by Django 2.2.4 on 2019-09-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190926_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='studio_name',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
